export type ConnectorStatus = "live" | "ready-with-env" | "partner-required" | "planned";
export type ConnectorAuthType = "oauth" | "api-key" | "iam-role" | "partner-api" | "manual" | "file-fallback";
export type ConnectorSyncMode = "webhook" | "polling" | "scheduled" | "manual" | "fallback";
export type ConnectorTrustClass = "direct-api" | "admin-api" | "receipt-evidence" | "regulated-partner" | "fallback-evidence";

export type ConnectorDataType =
  | "receipt"
  | "transaction"
  | "mandate"
  | "subscription"
  | "invoice"
  | "usage"
  | "cost"
  | "seat"
  | "workspace"
  | "evidence";

export type Connector = {
  id: string;
  name: string;
  phase: string;
  category: string;
  status: ConnectorStatus;
  authType: ConnectorAuthType;
  syncMode: ConnectorSyncMode;
  trustClass: ConnectorTrustClass;
  dataTypes: ConnectorDataType[];
  priority: number;
  realtimeCapable: boolean;
  userValue: string;
  evidence: string;
  requirements: string[];
  envVars?: string[];
  scopes?: string[];
  limitation?: string;
};

const connectorDefinitions: Connector[] = [
  {
    id: "gmail-readonly",
    name: "Gmail Read-Only",
    phase: "Phase 1",
    category: "Email",
    status: "ready-with-env",
    authType: "oauth",
    syncMode: "polling",
    trustClass: "receipt-evidence",
    dataTypes: ["receipt", "invoice", "evidence"],
    priority: 1,
    realtimeCapable: true,
    userValue: "Discover subscriptions from receipts and renewal emails without storing the full mailbox.",
    evidence: "OAuth start/callback endpoints exist and return receipt candidates from Gmail snippets.",
    requirements: ["Google OAuth app", "Restricted-scope verification", "Token vault for persistent sync"],
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REDIRECT_URI"],
    scopes: ["https://www.googleapis.com/auth/gmail.readonly"],
  },
  {
    id: "outlook-readonly",
    name: "Outlook / Microsoft 365 Mail",
    phase: "Phase 1",
    category: "Email",
    status: "planned",
    authType: "oauth",
    syncMode: "polling",
    trustClass: "receipt-evidence",
    dataTypes: ["receipt", "invoice", "evidence"],
    priority: 2,
    realtimeCapable: true,
    userValue: "Find renewal receipts in Microsoft mailboxes for users and teams that do not use Gmail.",
    evidence: "Same evidence model as Gmail; needs Microsoft Graph OAuth wiring.",
    requirements: ["Microsoft Entra app registration", "Mail.Read consent", "Webhook or delta-query sync"],
    scopes: ["Mail.Read", "offline_access"],
  },
  {
    id: "receipt-snippets",
    name: "Receipt Snippets",
    phase: "Phase 1",
    category: "Email",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "receipt-evidence",
    dataTypes: ["receipt", "invoice", "evidence"],
    priority: 3,
    realtimeCapable: false,
    userValue: "Convert pasted renewal emails into recurring candidates while live mail sync is being verified.",
    evidence: "Implemented through the Receipt Intelligence parser.",
    requirements: ["Receipt text pasted by user"],
  },
  {
    id: "openai-costs",
    name: "OpenAI Usage and Costs",
    phase: "Phase 2",
    category: "AI / Cloud Spend",
    status: "ready-with-env",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["usage", "cost", "workspace"],
    priority: 4,
    realtimeCapable: false,
    userValue: "Compare OpenAI spend against actual usage so teams can downgrade unused plans or cap runaway usage.",
    evidence: "OpenAI exposes organization usage endpoints and GET /organization/costs for admin accounts. Vognary has an env-gated cost adapter for first sync validation.",
    requirements: ["OPENAI_ADMIN_API_KEY", "Encrypted token storage for per-workspace production use", "Daily cost sync job"],
    envVars: ["OPENAI_ADMIN_API_KEY"],
  },
  {
    id: "anthropic-usage",
    name: "Anthropic / Claude Usage",
    phase: "Phase 2",
    category: "AI / Cloud Spend",
    status: "planned",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["usage", "cost", "workspace"],
    priority: 5,
    realtimeCapable: false,
    userValue: "Track Claude workspace usage against recurring AI tool spend where account APIs are available.",
    evidence: "Modeled as a provider adapter; endpoint availability must be verified per account tier.",
    requirements: ["Admin API access", "Usage/cost endpoint verification", "Encrypted token storage"],
    limitation: "Public cost API availability is not as clear as OpenAI; start as planned until credentials prove it.",
  },
  {
    id: "aws-cost-explorer",
    name: "AWS Cost Explorer",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "planned",
    authType: "iam-role",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["usage", "cost", "invoice"],
    priority: 6,
    realtimeCapable: false,
    userValue: "Detect recurring AWS spend, service spikes, and committed waste from Cost Explorer data.",
    evidence: "AWS Cost Explorer exposes cost and usage queries through ce.us-east-1.amazonaws.com with explicit IAM permission.",
    requirements: ["ce:GetCostAndUsage", "Cross-account role or access key", "Daily sync window"],
  },
  {
    id: "github-billing",
    name: "GitHub Billing",
    phase: "Phase 2",
    category: "Developer SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["cost", "seat", "workspace"],
    priority: 7,
    realtimeCapable: false,
    userValue: "Track GitHub org billing surfaces and paid security usage for engineering teams.",
    evidence: "GitHub exposes billing endpoints for organization and enterprise contexts.",
    requirements: ["GitHub App or OAuth app", "Org admin authorization", "Billing endpoint permissions"],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot Usage",
    phase: "Phase 2",
    category: "Developer SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["usage", "seat", "workspace"],
    priority: 8,
    realtimeCapable: false,
    userValue: "Find paid Copilot seats with low activity before renewal.",
    evidence: "GitHub exposes Copilot usage metrics and user-management endpoints for business/org contexts.",
    requirements: ["Org admin access", "Copilot Business or Enterprise", "Usage metrics permissions"],
  },
  {
    id: "cloudflare-billing",
    name: "Cloudflare Billing and Subscriptions",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "planned",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["subscription", "usage", "cost", "invoice"],
    priority: 9,
    realtimeCapable: false,
    userValue: "Track Cloudflare subscriptions, billing history, AI Gateway usage, and account-level costs.",
    evidence: "Cloudflare API includes account/user subscription, billing, usage, and AI Gateway billing resources.",
    requirements: ["Scoped Cloudflare API token", "Account ID", "Billing read permissions"],
  },
  {
    id: "render-platform",
    name: "Render Platform Usage",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "planned",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["usage", "workspace", "cost"],
    priority: 10,
    realtimeCapable: true,
    userValue: "Map Render services, instances, bandwidth, disk, and metrics to recurring infrastructure commitments.",
    evidence: "Render public REST API exposes services, owners, metrics, logs, events, and webhooks.",
    requirements: ["Render API key", "Workspace owner access", "Cost model mapping for plan and usage"],
    limitation: "Billing endpoints must be confirmed against the customer account; service and usage metrics are clearer than invoices.",
  },
  {
    id: "vercel-platform",
    name: "Vercel Usage and Billing",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "planned",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["usage", "cost", "workspace"],
    priority: 11,
    realtimeCapable: false,
    userValue: "Track Vercel team usage, analytics, and billing-related surfaces where account API access allows it.",
    evidence: "Modeled as a platform adapter; exact billing coverage needs endpoint-level validation.",
    requirements: ["Vercel token", "Team scope", "Usage endpoint verification"],
  },
  {
    id: "azure-cost-management",
    name: "Azure Cost Management",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["usage", "cost", "invoice"],
    priority: 12,
    realtimeCapable: false,
    userValue: "Track Azure recurring cloud spend for founder and enterprise workspaces.",
    evidence: "Cost Management APIs can query usage and cost data for authorized scopes.",
    requirements: ["Azure AD app", "Cost Management Reader", "Subscription or billing scope"],
  },
  {
    id: "google-cloud-billing",
    name: "Google Cloud Billing",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["usage", "cost", "invoice"],
    priority: 13,
    realtimeCapable: false,
    userValue: "Track GCP projects and billing accounts against recurring infrastructure commitments.",
    evidence: "Modeled for Cloud Billing export/API access through authorized billing account scopes.",
    requirements: ["Google Cloud project", "Billing account access", "Cloud Billing API permissions"],
  },
  {
    id: "stripe-billing",
    name: "Stripe Billing",
    phase: "Phase 2",
    category: "Merchant Billing",
    status: "planned",
    authType: "api-key",
    syncMode: "webhook",
    trustClass: "direct-api",
    dataTypes: ["subscription", "invoice", "cost"],
    priority: 14,
    realtimeCapable: true,
    userValue: "Help businesses map their own Stripe subscriptions, invoices, and recurring obligations.",
    evidence: "Adapter target for Stripe subscription and invoice records when the user owns the Stripe account.",
    requirements: ["Restricted Stripe API key", "Webhook endpoint", "Read-only billing scopes"],
    limitation: "This does not reveal arbitrary consumer subscriptions unless the user controls the Stripe account.",
  },
  {
    id: "paypal-automatic-payments",
    name: "PayPal Automatic Payments",
    phase: "Phase 3",
    category: "Wallets",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["subscription", "mandate", "invoice"],
    priority: 15,
    realtimeCapable: false,
    userValue: "Surface PayPal recurring payments when account permissions expose automatic-payment data.",
    evidence: "Modeled as a wallet connector; must validate exact user-level automatic-payment API access.",
    requirements: ["PayPal app", "User consent", "Automatic-payment endpoint validation"],
  },
  {
    id: "apple-receipt-evidence",
    name: "Apple Subscription Evidence",
    phase: "Phase 3",
    category: "App Stores",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "receipt-evidence",
    dataTypes: ["receipt", "subscription", "evidence"],
    priority: 16,
    realtimeCapable: false,
    userValue: "Capture Apple renewals from receipts or user-confirmed subscription screens.",
    evidence: "Manual mandate and receipt evidence paths are implemented.",
    requirements: ["Apple receipt email or user-confirmed source check"],
    limitation: "Apple App Store Server APIs are for developer-owned apps, not universal user-wide subscription discovery.",
  },
  {
    id: "google-play-receipt-evidence",
    name: "Google Play Subscription Evidence",
    phase: "Phase 3",
    category: "App Stores",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "receipt-evidence",
    dataTypes: ["receipt", "subscription", "evidence"],
    priority: 17,
    realtimeCapable: false,
    userValue: "Capture Google Play renewals from receipts or user-confirmed subscription screens.",
    evidence: "Manual mandate and receipt evidence paths are implemented.",
    requirements: ["Google Play receipt email or user-confirmed source check"],
    limitation: "Google Play Developer APIs manage developer-owned apps, not a universal user's Play subscriptions.",
  },
  {
    id: "app-store-server-api",
    name: "Apple App Store Server API",
    phase: "Phase 3",
    category: "Developer Revenue",
    status: "planned",
    authType: "api-key",
    syncMode: "webhook",
    trustClass: "admin-api",
    dataTypes: ["subscription", "invoice", "evidence"],
    priority: 18,
    realtimeCapable: true,
    userValue: "Support app developers who want subscription intelligence for their own Apple customers.",
    evidence: "Apple server APIs and notifications apply to developer-owned apps and customer transactions.",
    requirements: ["App Store Connect issuer/key", "Bundle IDs", "Server notification endpoint"],
  },
  {
    id: "google-play-developer-api",
    name: "Google Play Developer API",
    phase: "Phase 3",
    category: "Developer Revenue",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["subscription", "invoice", "evidence"],
    priority: 19,
    realtimeCapable: false,
    userValue: "Support app developers who need visibility into subscriptions for apps they own.",
    evidence: "Google Play Developer API can manage and inspect purchases for apps in the developer console.",
    requirements: ["Google Play Console access", "Service account or OAuth", "Package names"],
  },
  {
    id: "account-aggregator",
    name: "India Account Aggregator",
    phase: "Phase 4",
    category: "Open Finance",
    status: "partner-required",
    authType: "partner-api",
    syncMode: "scheduled",
    trustClass: "regulated-partner",
    dataTypes: ["transaction", "evidence"],
    priority: 20,
    realtimeCapable: false,
    userValue: "Consent-based bank account data without password scraping.",
    evidence: "Schema and source model support open-finance sources; FIU/TSP path is required.",
    requirements: ["FIU/TSP or regulated partner", "Consent artifact flow", "Compliance review"],
  },
  {
    id: "upi-autopay-mandates",
    name: "UPI AutoPay Mandates",
    phase: "Phase 5",
    category: "Mandates",
    status: "partner-required",
    authType: "partner-api",
    syncMode: "webhook",
    trustClass: "regulated-partner",
    dataTypes: ["mandate", "subscription", "evidence"],
    priority: 21,
    realtimeCapable: true,
    userValue: "Directly show active UPI AutoPay mandates and renewal amounts once provider access exists.",
    evidence: "Manual mandate workflow is live; direct sync requires UPI app, bank, PSP, or NPCI-connected partner access.",
    requirements: ["PSP/bank/payment-provider API", "Legal review", "Mandate lifecycle mapping"],
  },
  {
    id: "card-emandates",
    name: "Card E-Mandates",
    phase: "Phase 5",
    category: "Mandates",
    status: "partner-required",
    authType: "partner-api",
    syncMode: "webhook",
    trustClass: "regulated-partner",
    dataTypes: ["mandate", "subscription", "evidence"],
    priority: 22,
    realtimeCapable: true,
    userValue: "Show active card mandates, pre-debit notices, and merchant-level recurring card commitments.",
    evidence: "Manual mandate workflow is live; issuer/network/payment-aggregator access is required for direct sync.",
    requirements: ["Issuer or payment aggregator access", "Mandate state API", "Cancellation and modification policy mapping"],
  },
  {
    id: "razorpay-merchant-mandates",
    name: "Razorpay Merchant Mandates",
    phase: "Phase 5",
    category: "Merchant Billing",
    status: "partner-required",
    authType: "api-key",
    syncMode: "webhook",
    trustClass: "admin-api",
    dataTypes: ["mandate", "subscription", "invoice"],
    priority: 23,
    realtimeCapable: true,
    userValue: "Let Indian merchants audit subscriptions and mandates they collect through Razorpay.",
    evidence: "Merchant-side mandate visibility is plausible; consumer-wide UPI visibility is not the same API surface.",
    requirements: ["Merchant API credentials", "Webhook endpoint", "Read-only payment/subscription scopes"],
  },
  {
    id: "cashfree-merchant-mandates",
    name: "Cashfree Merchant Mandates",
    phase: "Phase 5",
    category: "Merchant Billing",
    status: "planned",
    authType: "api-key",
    syncMode: "webhook",
    trustClass: "admin-api",
    dataTypes: ["mandate", "subscription", "invoice"],
    priority: 24,
    realtimeCapable: true,
    userValue: "Audit recurring collections for merchants using Cashfree or similar Indian payment stacks.",
    evidence: "Modeled as a merchant-side payment connector.",
    requirements: ["Merchant API credentials", "Webhook endpoint", "Read-only payment/subscription scopes"],
  },
  {
    id: "slack-admin",
    name: "Slack Admin Billing Evidence",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 25,
    realtimeCapable: false,
    userValue: "Find paid collaboration seats and inactive users that drive recurring workspace spend.",
    evidence: "Seat and workspace adapter target; billing details depend on admin API availability and plan.",
    requirements: ["Workspace admin consent", "SCIM/admin API access", "Seat-to-plan cost mapping"],
  },
  {
    id: "notion-admin",
    name: "Notion Workspace Seats",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 26,
    realtimeCapable: false,
    userValue: "Map Notion workspace seats to recurring SaaS cost and ownership.",
    evidence: "Seat-level connector target; exact billing depth depends on workspace admin APIs.",
    requirements: ["Workspace owner access", "User list permission", "Plan cost mapping"],
  },
  {
    id: "atlassian-admin",
    name: "Atlassian Admin",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 27,
    realtimeCapable: false,
    userValue: "Track Jira, Confluence, and Atlassian seat commitments before renewal.",
    evidence: "Admin connector target for users, products, and seat counts.",
    requirements: ["Atlassian admin consent", "Organization scope", "Product plan mapping"],
  },
  {
    id: "figma-admin",
    name: "Figma Admin",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 28,
    realtimeCapable: false,
    userValue: "Find unused paid design seats and ownerless teams.",
    evidence: "Seat/workspace adapter target for admin-authorized organizations.",
    requirements: ["Figma admin access", "Team/member endpoint access", "Plan cost mapping"],
  },
  {
    id: "linear-admin",
    name: "Linear Workspace",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 29,
    realtimeCapable: false,
    userValue: "Track product-team workspace seats against recurring SaaS spend.",
    evidence: "Workspace adapter target for member and billing evidence where APIs expose it.",
    requirements: ["Workspace admin access", "Member list access", "Plan cost mapping"],
  },
  {
    id: "zoom-admin",
    name: "Zoom Admin",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 30,
    realtimeCapable: false,
    userValue: "Audit Zoom licenses, add-ons, and low-usage paid seats.",
    evidence: "Admin connector target for users, plans, and usage evidence.",
    requirements: ["Zoom admin consent", "User and report scopes", "Plan cost mapping"],
  },
  {
    id: "godaddy-domains",
    name: "GoDaddy Domains",
    phase: "Phase 6",
    category: "Domains",
    status: "planned",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["subscription", "invoice", "evidence"],
    priority: 31,
    realtimeCapable: false,
    userValue: "Track domain renewals that often get missed in normal bank transaction views.",
    evidence: "Domain registrar adapter target for renewal dates and auto-renew evidence.",
    requirements: ["Registrar API key", "Domain list access", "Renewal price mapping"],
  },
  {
    id: "namecheap-domains",
    name: "Namecheap Domains",
    phase: "Phase 6",
    category: "Domains",
    status: "planned",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["subscription", "invoice", "evidence"],
    priority: 32,
    realtimeCapable: false,
    userValue: "Track Namecheap domain and hosting renewals from registrar data.",
    evidence: "Domain registrar adapter target for renewal dates and auto-renew evidence.",
    requirements: ["Registrar API key", "Domain list access", "Renewal price mapping"],
  },
  {
    id: "insurance-renewals",
    name: "Insurance Renewals",
    phase: "Phase 7",
    category: "Consumer Finance",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "fallback-evidence",
    dataTypes: ["invoice", "evidence", "subscription"],
    priority: 33,
    realtimeCapable: false,
    userValue: "Track annual insurance renewals that do not expose consumer APIs.",
    evidence: "Manual evidence and receipt parser can represent these as recurring commitments.",
    requirements: ["Policy receipt", "Renewal amount", "User confirmation"],
  },
  {
    id: "utilities-renewals",
    name: "Utilities and Telecom",
    phase: "Phase 7",
    category: "Consumer Finance",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "fallback-evidence",
    dataTypes: ["invoice", "evidence", "subscription"],
    priority: 34,
    realtimeCapable: false,
    userValue: "Track broadband, mobile, electricity, and similar recurring household payments.",
    evidence: "Manual evidence and receipt parser can represent these until biller APIs are available.",
    requirements: ["Bill receipt", "Provider account check", "User confirmation"],
  },
  {
    id: "bank-issuer-white-label",
    name: "Bank/Issuer White Label",
    phase: "Phase 8",
    category: "B2B",
    status: "partner-required",
    authType: "partner-api",
    syncMode: "webhook",
    trustClass: "regulated-partner",
    dataTypes: ["transaction", "mandate", "subscription", "evidence"],
    priority: 35,
    realtimeCapable: true,
    userValue: "Embed Vognary recurring intelligence into bank/card apps with issuer-grade data access.",
    evidence: "Audit APIs and connector registry are ready for pilot conversations.",
    requirements: ["Signed pilot", "Security review", "SLA and data processing agreement"],
  },
  {
    id: "statement-imports",
    name: "Statement Import Fallback",
    phase: "Fallback",
    category: "Statements",
    status: "live",
    authType: "file-fallback",
    syncMode: "fallback",
    trustClass: "fallback-evidence",
    dataTypes: ["transaction", "evidence"],
    priority: 90,
    realtimeCapable: false,
    userValue: "Import bank and card statement exports only when direct source access is unavailable.",
    evidence: "Implemented through /api/ingest and browser upload.",
    requirements: ["User-exported statement", "Used only when no live connector exists"],
  },
  {
    id: "pdf-statements",
    name: "PDF Statement Fallback",
    phase: "Fallback",
    category: "Statements",
    status: "live",
    authType: "file-fallback",
    syncMode: "fallback",
    trustClass: "fallback-evidence",
    dataTypes: ["transaction", "evidence"],
    priority: 91,
    realtimeCapable: false,
    userValue: "Upload readable PDFs when CSV is unavailable, then verify converted rows.",
    evidence: "Implemented with stateless PDF text extraction and warning labels.",
    requirements: ["Readable PDF", "User verification for converted rows"],
  },
  {
    id: "manual-mandates",
    name: "Manual Mandate Fallback",
    phase: "Fallback",
    category: "Mandates",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "fallback-evidence",
    dataTypes: ["mandate", "subscription", "evidence"],
    priority: 92,
    realtimeCapable: false,
    userValue: "Add Apple, Google Play, UPI AutoPay, card mandates, domains, insurance, SIPs, EMIs, and utilities.",
    evidence: "Implemented with manual templates and evidence trail.",
    requirements: ["User checks source app/dashboard"],
  },
  {
    id: "team-workspaces",
    name: "Team Review Workflow",
    phase: "Product Layer",
    category: "Teams",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "fallback-evidence",
    dataTypes: ["workspace", "evidence"],
    priority: 93,
    realtimeCapable: false,
    userValue: "Assign recurring spend to owners and complete monthly reviews.",
    evidence: "Implemented locally with owner assignment, notes, and review completion.",
    requirements: ["Optional account persistence for multi-user sync"],
  },
];

export const connectors = [...connectorDefinitions].sort((left, right) => left.priority - right.priority);

export function getConnectorSummary() {
  return connectors.reduce<Record<ConnectorStatus, number>>((summary, connector) => {
    summary[connector.status] = (summary[connector.status] ?? 0) + 1;
    return summary;
  }, { live: 0, "ready-with-env": 0, "partner-required": 0, planned: 0 });
}

export function getConnectorSyncSummary() {
  return connectors.reduce(
    (summary, connector) => {
      summary.total += 1;
      summary.realtimeCapable += connector.realtimeCapable ? 1 : 0;
      summary.byAuthType[connector.authType] = (summary.byAuthType[connector.authType] ?? 0) + 1;
      summary.byTrustClass[connector.trustClass] = (summary.byTrustClass[connector.trustClass] ?? 0) + 1;
      return summary;
    },
    {
      total: 0,
      realtimeCapable: 0,
      byAuthType: {} as Record<ConnectorAuthType, number>,
      byTrustClass: {} as Record<ConnectorTrustClass, number>,
    },
  );
}

export function getConnectorById(id: string) {
  return connectors.find((connector) => connector.id === id);
}