export type ConnectorStatus = "live" | "ready-with-env" | "partner-required" | "planned";
export type ConnectorAuthType = "oauth" | "api-key" | "iam-role" | "partner-api" | "manual" | "file-fallback";
export type ConnectorSyncMode = "webhook" | "polling" | "scheduled" | "manual" | "fallback";
export type ConnectorTrustClass = "direct-api" | "admin-api" | "receipt-evidence" | "regulated-partner" | "fallback-evidence";

export type ConnectorDataType =
  | "receipt"
  | "transaction"
  | "mandate"
  | "subscription"
  | "invoice"
  | "usage"
  | "cost"
  | "seat"
  | "workspace"
  | "evidence";

export type Connector = {
  id: string;
  name: string;
  phase: string;
  category: string;
  status: ConnectorStatus;
  authType: ConnectorAuthType;
  syncMode: ConnectorSyncMode;
  trustClass: ConnectorTrustClass;
  dataTypes: ConnectorDataType[];
  priority: number;
  realtimeCapable: boolean;
  userValue: string;
  evidence: string;
  requirements: string[];
  envVars?: string[];
  scopes?: string[];
  limitation?: string;
  materialization?: "financial" | "usage-only" | "source-health-only";
};

const connectorDefinitions: Connector[] = [
  {
    id: "gmail-readonly",
    name: "Gmail Read-Only",
    phase: "Phase 1",
    category: "Email",
    status: "ready-with-env",
    authType: "oauth",
    syncMode: "polling",
    trustClass: "receipt-evidence",
    dataTypes: ["receipt", "invoice", "evidence"],
    priority: 1,
    realtimeCapable: true,
    userValue: "Discover subscriptions from receipts and renewal emails without storing the full mailbox.",
    evidence: "OAuth start/callback endpoints exist and return receipt candidates from Gmail snippets.",
    requirements: ["Google OAuth app", "Restricted-scope verification", "Token vault for persistent sync"],
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REDIRECT_URI"],
    scopes: ["https://www.googleapis.com/auth/gmail.readonly"],
  },
  {
    id: "outlook-readonly",
    name: "Outlook / Microsoft 365 Mail",
    phase: "Phase 1",
    category: "Email",
    status: "planned",
    authType: "oauth",
    syncMode: "polling",
    trustClass: "receipt-evidence",
    dataTypes: ["receipt", "invoice", "evidence"],
    priority: 2,
    realtimeCapable: true,
    userValue: "Find renewal receipts in Microsoft mailboxes for users and teams that do not use Gmail.",
    evidence: "Same evidence model as Gmail; needs Microsoft Graph OAuth wiring.",
    requirements: ["Microsoft Entra app registration", "Mail.Read consent", "Webhook or delta-query sync"],
    scopes: ["Mail.Read", "offline_access"],
  },
  {
    id: "receipt-snippets",
    name: "Receipt Snippets",
    phase: "Phase 1",
    category: "Email",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "receipt-evidence",
    dataTypes: ["receipt", "invoice", "evidence"],
    priority: 3,
    realtimeCapable: false,
    userValue: "Convert pasted renewal emails into recurring candidates while live mail sync is being verified.",
    evidence: "Implemented through the Receipt Intelligence parser.",
    requirements: ["Receipt text pasted by user"],
  },
  {
    id: "openai-costs",
    name: "OpenAI Usage and Costs",
    phase: "Phase 2",
    category: "AI / Cloud Spend",
    status: "live",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["usage", "cost", "workspace"],
    priority: 4,
    realtimeCapable: false,
    userValue: "Compare OpenAI spend against actual usage so teams can downgrade unused plans or cap runaway usage.",
    evidence: "OpenAI exposes GET /organization/costs for admin accounts. Production sync uses a per-workspace key from encrypted connector storage; a global key is limited to an explicit non-production preview.",
    requirements: ["Workspace-scoped OpenAI Admin API key", "Encrypted token storage", "Daily cost sync job"],
    materialization: "usage-only",
  },
  {
    id: "anthropic-usage",
    name: "Anthropic / Claude Usage",
    phase: "Phase 2",
    category: "AI / Cloud Spend",
    status: "live",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["usage", "cost", "workspace"],
    priority: 5,
    realtimeCapable: false,
    userValue: "Track Anthropic organization API costs against recurring AI tool spend, grouped by cost description.",
    evidence: "Reads GET /v1/organizations/cost_report (Admin API, daily USD buckets); endpoint verified against published documentation 2026-07-16.",
    requirements: ["Anthropic Admin API key (sk-ant-admin…)", "Organization account (individual accounts are not eligible)", "Encrypted token storage"],
    limitation: "Cost data covers organization accounts only and appears with up to a few minutes of delay; Claude subscription (non-API) spend is not included.",
  },
  {
    id: "claude-subscription",
    name: "Claude Subscription",
    phase: "Phase 2",
    category: "AI / Consumer SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["subscription", "invoice", "usage"],
    priority: 5.1,
    realtimeCapable: false,
    userValue: "Let users connect Claude billing and usage so recurring AI spend appears without manual entry.",
    evidence: "Connector target is modeled; direct consumer subscription API access must be confirmed with Anthropic.",
    requirements: ["Official Claude account API or partner access", "User consent flow", "Encrypted token storage"],
    limitation: "Claude consumer billing does not expose a universal public subscription API today; launch starts with official account handoff until provider access exists.",
  },
  {
    id: "kling-subscription",
    name: "Kling Subscription",
    phase: "Phase 2",
    category: "AI / Consumer SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["subscription", "invoice", "usage"],
    priority: 5.2,
    realtimeCapable: false,
    userValue: "Track Kling plan renewals and usage once an official account or billing integration is available.",
    evidence: "Connector target is modeled for user-authorized subscription evidence.",
    requirements: ["Official Kling account API or partner access", "User consent flow", "Plan and renewal mapper"],
    limitation: "Use official-account handoff until a supported user billing API is available.",
  },
  {
    id: "x-premium-subscription",
    name: "X Premium",
    phase: "Phase 2",
    category: "Consumer SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["subscription", "invoice"],
    priority: 5.3,
    realtimeCapable: false,
    userValue: "Show X Premium renewals in the same recurring ledger as AI tools, cloud, app-store, and mandate spend.",
    evidence: "Connector target is modeled; official billing visibility depends on X account APIs or partner access.",
    requirements: ["Official X account/billing API", "User consent flow", "Renewal and plan mapper"],
    limitation: "Use official-account handoff until user subscription APIs are available.",
  },
  {
    id: "aws-cost-explorer",
    name: "AWS Cost Explorer",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "planned",
    authType: "iam-role",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["usage", "cost", "invoice"],
    priority: 6,
    realtimeCapable: false,
    userValue: "Detect recurring AWS spend, service spikes, and committed waste from Cost Explorer data.",
    evidence: "AWS Cost Explorer exposes cost and usage queries through ce.us-east-1.amazonaws.com with explicit IAM permission.",
    requirements: ["ce:GetCostAndUsage", "Cross-account role or access key", "Daily sync window"],
  },
  {
    id: "github-billing",
    name: "GitHub Billing",
    phase: "Phase 2",
    category: "Developer SaaS",
    status: "live",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["cost", "seat", "workspace"],
    priority: 7,
    realtimeCapable: false,
    userValue: "Track GitHub organization billing usage (Actions, Packages, Copilot, storage) aggregated per product.",
    evidence: "Reads GET /organizations/{org}/settings/billing/usage (enhanced billing platform); endpoint verified against published documentation 2026-07-16.",
    requirements: ["GitHub token with organization billing read access", "Organization admin authorization", "Enhanced billing platform (newer GitHub org accounts)"],
    limitation: "Only organizations on GitHub's enhanced billing platform expose this endpoint; legacy billing orgs are not covered.",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot Usage",
    phase: "Phase 2",
    category: "Developer SaaS",
    status: "live",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["usage", "seat", "workspace"],
    priority: 8,
    realtimeCapable: false,
    userValue: "Find paid Copilot seats with low activity before renewal.",
    evidence: "Registered adapter stores the availability and date range of GitHub's organization Copilot report. It does not yet download report rows or produce seat-cost observations.",
    requirements: ["GitHub organization slug", "Token with read:org or Copilot metrics permission", "Copilot Business or Enterprise"],
    scopes: ["read:org"],
    materialization: "source-health-only",
  },
  {
    id: "cloudflare-billing",
    name: "Cloudflare Billing and Subscriptions",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "live",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["workspace", "evidence"],
    priority: 9,
    realtimeCapable: false,
    userValue: "Confirm which Cloudflare accounts are connected and whether their inventory sync is healthy.",
    evidence: "Registered adapter calls Cloudflare's official account-list endpoint and stores account inventory. The current endpoint returns no billing amount, so it does not populate spend or commitments.",
    requirements: ["Scoped Cloudflare API token", "Account read permission"],
    materialization: "source-health-only",
  },
  {
    id: "render-platform",
    name: "Render Platform Usage",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "live",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["usage", "workspace", "cost"],
    priority: 10,
    realtimeCapable: true,
    userValue: "Confirm which Render services are connected and whether their inventory sync is healthy.",
    evidence: "Registered adapter calls Render's official list-services endpoint and stores service inventory. The current endpoint returns no billing amount, so it does not populate spend or commitments.",
    requirements: ["Render API key", "Workspace owner access"],
    limitation: "Service presence sync is implemented; exact invoice/cost mapping still needs a validated billing endpoint.",
    materialization: "source-health-only",
  },
  {
    id: "vercel-platform",
    name: "Vercel Usage and Billing",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "live",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["usage", "cost", "workspace", "subscription"],
    priority: 11,
    realtimeCapable: false,
    userValue: "Track connected Vercel domain inventory and renewal dates as a coverage signal.",
    evidence: "Registered adapter calls Vercel's official domain-list endpoint and stores domain renewal inventory. The response has no renewal amount, so it does not populate spend or commitments.",
    requirements: ["Vercel token", "Optional team slug", "Domain read access"],
    materialization: "source-health-only",
  },
  {
    id: "azure-cost-management",
    name: "Azure Cost Management",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["usage", "cost", "invoice"],
    priority: 12,
    realtimeCapable: false,
    userValue: "Track Azure recurring cloud spend for founder and enterprise workspaces.",
    evidence: "Cost Management APIs can query usage and cost data for authorized scopes.",
    requirements: ["Azure AD app", "Cost Management Reader", "Subscription or billing scope"],
  },
  {
    id: "google-cloud-billing",
    name: "Google Cloud Billing",
    phase: "Phase 2",
    category: "Cloud Spend",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["usage", "cost", "invoice"],
    priority: 13,
    realtimeCapable: false,
    userValue: "Track GCP projects and billing accounts against recurring infrastructure commitments.",
    evidence: "Modeled for Cloud Billing export/API access through authorized billing account scopes.",
    requirements: ["Google Cloud project", "Billing account access", "Cloud Billing API permissions"],
  },
  {
    id: "stripe-billing",
    name: "Stripe Billing",
    phase: "Phase 2",
    category: "Merchant Billing",
    status: "planned",
    authType: "api-key",
    syncMode: "webhook",
    trustClass: "direct-api",
    dataTypes: ["subscription", "invoice", "cost"],
    priority: 14,
    realtimeCapable: true,
    userValue: "Help businesses map their own Stripe subscriptions, invoices, and recurring obligations.",
    evidence: "Adapter target for Stripe subscription and invoice records when the user owns the Stripe account.",
    requirements: ["Restricted Stripe API key", "Webhook endpoint", "Read-only billing scopes"],
    limitation: "This does not reveal arbitrary consumer subscriptions unless the user controls the Stripe account.",
  },
  {
    id: "paypal-automatic-payments",
    name: "PayPal Automatic Payments",
    phase: "Phase 3",
    category: "Wallets",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["subscription", "mandate", "invoice"],
    priority: 15,
    realtimeCapable: false,
    userValue: "Surface PayPal recurring payments when account permissions expose automatic-payment data.",
    evidence: "Modeled as a wallet connector; must validate exact user-level automatic-payment API access.",
    requirements: ["PayPal app", "User consent", "Automatic-payment endpoint validation"],
  },
  {
    id: "apple-receipt-evidence",
    name: "Apple Subscription Evidence",
    phase: "Phase 3",
    category: "App Stores",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "receipt-evidence",
    dataTypes: ["receipt", "subscription", "evidence"],
    priority: 16,
    realtimeCapable: false,
    userValue: "Capture Apple renewals from receipts or user-confirmed subscription screens.",
    evidence: "Manual mandate and receipt evidence paths are implemented.",
    requirements: ["Apple receipt email or user-confirmed source check"],
    limitation: "Apple App Store Server APIs are for developer-owned apps, not universal user-wide subscription discovery.",
  },
  {
    id: "google-play-receipt-evidence",
    name: "Google Play Subscription Evidence",
    phase: "Phase 3",
    category: "App Stores",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "receipt-evidence",
    dataTypes: ["receipt", "subscription", "evidence"],
    priority: 17,
    realtimeCapable: false,
    userValue: "Capture Google Play renewals from receipts or user-confirmed subscription screens.",
    evidence: "Manual mandate and receipt evidence paths are implemented.",
    requirements: ["Google Play receipt email or user-confirmed source check"],
    limitation: "Google Play Developer APIs manage developer-owned apps, not a universal user's Play subscriptions.",
  },
  {
    id: "app-store-server-api",
    name: "Apple App Store Server API",
    phase: "Phase 3",
    category: "Developer Revenue",
    status: "planned",
    authType: "api-key",
    syncMode: "webhook",
    trustClass: "admin-api",
    dataTypes: ["subscription", "invoice", "evidence"],
    priority: 18,
    realtimeCapable: true,
    userValue: "Support app developers who want subscription intelligence for their own Apple customers.",
    evidence: "Apple server APIs and notifications apply to developer-owned apps and customer transactions.",
    requirements: ["App Store Connect issuer/key", "Bundle IDs", "Server notification endpoint"],
  },
  {
    id: "google-play-developer-api",
    name: "Google Play Developer API",
    phase: "Phase 3",
    category: "Developer Revenue",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["subscription", "invoice", "evidence"],
    priority: 19,
    realtimeCapable: false,
    userValue: "Support app developers who need visibility into subscriptions for apps they own.",
    evidence: "Google Play Developer API can manage and inspect purchases for apps in the developer console.",
    requirements: ["Google Play Console access", "Service account or OAuth", "Package names"],
  },
  {
    id: "account-aggregator",
    name: "India Account Aggregator",
    phase: "Phase 4",
    category: "Open Finance",
    status: "partner-required",
    authType: "partner-api",
    syncMode: "scheduled",
    trustClass: "regulated-partner",
    dataTypes: ["transaction", "evidence"],
    priority: 20,
    realtimeCapable: false,
    userValue: "Consent-based bank account data without password scraping.",
    evidence: "Schema and source model support open-finance sources; FIU/TSP path is required.",
    requirements: ["FIU/TSP or regulated partner", "Consent artifact flow", "Compliance review"],
  },
  {
    id: "upi-autopay-mandates",
    name: "UPI AutoPay Mandates",
    phase: "Phase 5",
    category: "Mandates",
    status: "partner-required",
    authType: "partner-api",
    syncMode: "webhook",
    trustClass: "regulated-partner",
    dataTypes: ["mandate", "subscription", "evidence"],
    priority: 21,
    realtimeCapable: true,
    userValue: "Directly show active UPI AutoPay mandates and renewal amounts once provider access exists.",
    evidence: "Manual mandate workflow is live; direct sync requires UPI app, bank, PSP, or NPCI-connected partner access.",
    requirements: ["PSP/bank/payment-provider API", "Legal review", "Mandate lifecycle mapping"],
  },
  {
    id: "card-emandates",
    name: "Card E-Mandates",
    phase: "Phase 5",
    category: "Mandates",
    status: "partner-required",
    authType: "partner-api",
    syncMode: "webhook",
    trustClass: "regulated-partner",
    dataTypes: ["mandate", "subscription", "evidence"],
    priority: 22,
    realtimeCapable: true,
    userValue: "Show active card mandates, pre-debit notices, and merchant-level recurring card commitments.",
    evidence: "Manual mandate workflow is live; issuer/network/payment-aggregator access is required for direct sync.",
    requirements: ["Issuer or payment aggregator access", "Mandate state API", "Cancellation and modification policy mapping"],
  },
  {
    id: "razorpay-merchant-mandates",
    name: "Razorpay Merchant Mandates",
    phase: "Phase 5",
    category: "Merchant Billing",
    status: "partner-required",
    authType: "api-key",
    syncMode: "webhook",
    trustClass: "admin-api",
    dataTypes: ["mandate", "subscription", "invoice"],
    priority: 23,
    realtimeCapable: true,
    userValue: "Let Indian merchants audit subscriptions and mandates they collect through Razorpay.",
    evidence: "Merchant-side mandate visibility is plausible; consumer-wide UPI visibility is not the same API surface.",
    requirements: ["Merchant API credentials", "Webhook endpoint", "Read-only payment/subscription scopes"],
  },
  {
    id: "cashfree-merchant-mandates",
    name: "Cashfree Merchant Mandates",
    phase: "Phase 5",
    category: "Merchant Billing",
    status: "planned",
    authType: "api-key",
    syncMode: "webhook",
    trustClass: "admin-api",
    dataTypes: ["mandate", "subscription", "invoice"],
    priority: 24,
    realtimeCapable: true,
    userValue: "Audit recurring collections for merchants using Cashfree or similar Indian payment stacks.",
    evidence: "Modeled as a merchant-side payment connector.",
    requirements: ["Merchant API credentials", "Webhook endpoint", "Read-only payment/subscription scopes"],
  },
  {
    id: "slack-admin",
    name: "Slack Admin Billing Evidence",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 25,
    realtimeCapable: false,
    userValue: "Find paid collaboration seats and inactive users that drive recurring workspace spend.",
    evidence: "Seat and workspace adapter target; billing details depend on admin API availability and plan.",
    requirements: ["Workspace admin consent", "SCIM/admin API access", "Seat-to-plan cost mapping"],
  },
  {
    id: "notion-admin",
    name: "Notion Workspace Seats",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 26,
    realtimeCapable: false,
    userValue: "Map Notion workspace seats to recurring SaaS cost and ownership.",
    evidence: "Seat-level connector target; exact billing depth depends on workspace admin APIs.",
    requirements: ["Workspace owner access", "User list permission", "Plan cost mapping"],
  },
  {
    id: "atlassian-admin",
    name: "Atlassian Admin",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 27,
    realtimeCapable: false,
    userValue: "Track Jira, Confluence, and Atlassian seat commitments before renewal.",
    evidence: "Admin connector target for users, products, and seat counts.",
    requirements: ["Atlassian admin consent", "Organization scope", "Product plan mapping"],
  },
  {
    id: "figma-admin",
    name: "Figma Admin",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 28,
    realtimeCapable: false,
    userValue: "Find unused paid design seats and ownerless teams.",
    evidence: "Seat/workspace adapter target for admin-authorized organizations.",
    requirements: ["Figma admin access", "Team/member endpoint access", "Plan cost mapping"],
  },
  {
    id: "linear-admin",
    name: "Linear Workspace",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 29,
    realtimeCapable: false,
    userValue: "Track product-team workspace seats against recurring SaaS spend.",
    evidence: "Workspace adapter target for member and billing evidence where APIs expose it.",
    requirements: ["Workspace admin access", "Member list access", "Plan cost mapping"],
  },
  {
    id: "zoom-admin",
    name: "Zoom Admin",
    phase: "Phase 6",
    category: "Team SaaS",
    status: "planned",
    authType: "oauth",
    syncMode: "scheduled",
    trustClass: "admin-api",
    dataTypes: ["seat", "workspace", "cost"],
    priority: 30,
    realtimeCapable: false,
    userValue: "Audit Zoom licenses, add-ons, and low-usage paid seats.",
    evidence: "Admin connector target for users, plans, and usage evidence.",
    requirements: ["Zoom admin consent", "User and report scopes", "Plan cost mapping"],
  },
  {
    id: "godaddy-domains",
    name: "GoDaddy Domains",
    phase: "Phase 6",
    category: "Domains",
    status: "planned",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["subscription", "invoice", "evidence"],
    priority: 31,
    realtimeCapable: false,
    userValue: "Track domain renewals that often get missed in normal bank transaction views.",
    evidence: "Domain registrar adapter target for renewal dates and auto-renew evidence.",
    requirements: ["Registrar API key", "Domain list access", "Renewal price mapping"],
  },
  {
    id: "namecheap-domains",
    name: "Namecheap Domains",
    phase: "Phase 6",
    category: "Domains",
    status: "planned",
    authType: "api-key",
    syncMode: "scheduled",
    trustClass: "direct-api",
    dataTypes: ["subscription", "invoice", "evidence"],
    priority: 32,
    realtimeCapable: false,
    userValue: "Track Namecheap domain and hosting renewals from registrar data.",
    evidence: "Domain registrar adapter target for renewal dates and auto-renew evidence.",
    requirements: ["Registrar API key", "Domain list access", "Renewal price mapping"],
  },
  {
    id: "insurance-renewals",
    name: "Insurance Renewals",
    phase: "Phase 7",
    category: "Consumer Finance",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "fallback-evidence",
    dataTypes: ["invoice", "evidence", "subscription"],
    priority: 33,
    realtimeCapable: false,
    userValue: "Track annual insurance renewals that do not expose consumer APIs.",
    evidence: "Manual evidence and receipt parser can represent these as recurring commitments.",
    requirements: ["Policy receipt", "Renewal amount", "User confirmation"],
  },
  {
    id: "utilities-renewals",
    name: "Utilities and Telecom",
    phase: "Phase 7",
    category: "Consumer Finance",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "fallback-evidence",
    dataTypes: ["invoice", "evidence", "subscription"],
    priority: 34,
    realtimeCapable: false,
    userValue: "Track broadband, mobile, electricity, and similar recurring household payments.",
    evidence: "Manual evidence and receipt parser can represent these until biller APIs are available.",
    requirements: ["Bill receipt", "Provider account check", "User confirmation"],
  },
  {
    id: "bank-issuer-white-label",
    name: "Bank/Issuer White Label",
    phase: "Phase 8",
    category: "B2B",
    status: "partner-required",
    authType: "partner-api",
    syncMode: "webhook",
    trustClass: "regulated-partner",
    dataTypes: ["transaction", "mandate", "subscription", "evidence"],
    priority: 35,
    realtimeCapable: true,
    userValue: "Embed Vognary recurring intelligence into bank/card apps with issuer-grade data access.",
    evidence: "Audit APIs and connector registry are ready for pilot conversations.",
    requirements: ["Signed pilot", "Security review", "SLA and data processing agreement"],
  },
  {
    id: "statement-imports",
    name: "Statement Import Fallback",
    phase: "Fallback",
    category: "Statements",
    status: "live",
    authType: "file-fallback",
    syncMode: "fallback",
    trustClass: "fallback-evidence",
    dataTypes: ["transaction", "evidence"],
    priority: 90,
    realtimeCapable: false,
    userValue: "Import bank and card statement exports only when direct source access is unavailable.",
    evidence: "Implemented through /api/ingest and browser upload.",
    requirements: ["User-exported statement", "Used only when no live connector exists"],
  },
  {
    id: "pdf-statements",
    name: "PDF Statement Fallback",
    phase: "Fallback",
    category: "Statements",
    status: "live",
    authType: "file-fallback",
    syncMode: "fallback",
    trustClass: "fallback-evidence",
    dataTypes: ["transaction", "evidence"],
    priority: 91,
    realtimeCapable: false,
    userValue: "Upload readable PDFs when CSV is unavailable, then verify converted rows.",
    evidence: "Implemented with stateless PDF text extraction and warning labels.",
    requirements: ["Readable PDF", "User verification for converted rows"],
  },
  {
    id: "manual-mandates",
    name: "Manual Mandate Fallback",
    phase: "Fallback",
    category: "Mandates",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "fallback-evidence",
    dataTypes: ["mandate", "subscription", "evidence"],
    priority: 92,
    realtimeCapable: false,
    userValue: "Add Apple, Google Play, UPI AutoPay, card mandates, domains, insurance, SIPs, EMIs, and utilities.",
    evidence: "Implemented with manual templates and evidence trail.",
    requirements: ["User checks source app/dashboard"],
  },
  {
    id: "team-workspaces",
    name: "Team Review Workflow",
    phase: "Product Layer",
    category: "Teams",
    status: "live",
    authType: "manual",
    syncMode: "manual",
    trustClass: "fallback-evidence",
    dataTypes: ["workspace", "evidence"],
    priority: 93,
    realtimeCapable: false,
    userValue: "Assign recurring spend to owners and complete monthly reviews.",
    evidence: "Implemented locally with owner assignment, notes, and review completion.",
    requirements: ["Optional account persistence for multi-user sync"],
  },
];

export const connectors = [...connectorDefinitions].sort((left, right) => left.priority - right.priority);

// The fine-grained truth vocabulary shown to users. Derived from status, auth
// type, and runtime env state so a connector can never claim more readiness
// than its weakest missing requirement.
export type ConnectorHonestyState =
  | "live"
  | "usage-only"
  | "source-health-only"
  | "setup-ready"
  | "token-required"
  | "oauth-required"
  | "verification-required"
  | "partner-gated"
  | "blocked"
  | "evidence-only"
  | "planned";

export type ConnectorHonestyContext = {
  envConfigured?: boolean;
  verificationComplete?: boolean;
};

export function getConnectorHonestyState(connector: Connector, context: ConnectorHonestyContext = {}): ConnectorHonestyState {
  if (connector.status === "partner-required") return "partner-gated";
  if (connector.status === "planned") return "planned";

  const evidenceOnly = connector.authType === "manual" || connector.authType === "file-fallback";
  if (connector.status === "live") {
    if (evidenceOnly) return "evidence-only";
    if (connector.materialization === "source-health-only") return "source-health-only";
    if (connector.materialization === "usage-only") return "usage-only";
    return "live";
  }

  // status === "ready-with-env": the code path exists but activation is pending.
  if (connector.authType === "api-key") return "token-required";
  if (connector.authType === "oauth") {
    if (!context.envConfigured) return "oauth-required";
    return context.verificationComplete ? "setup-ready" : "verification-required";
  }
  if (connector.authType === "iam-role" || connector.authType === "partner-api") {
    return context.envConfigured ? "setup-ready" : "blocked";
  }
  return "setup-ready";
}

export const connectorHonestyStateLabels: Record<ConnectorHonestyState, string> = {
  live: "Live",
  "usage-only": "Usage/cost only",
  "source-health-only": "Source health only",
  "setup-ready": "Setup ready",
  "token-required": "Token required",
  "oauth-required": "OAuth app required",
  "verification-required": "Verification pending",
  "partner-gated": "Partner gated",
  blocked: "Blocked",
  "evidence-only": "Evidence path",
  planned: "Planned",
};

export const connectorHonestyStateMeanings: Record<ConnectorHonestyState, string> = {
  live: "Users can connect through an official path and the current adapter writes financial ledger evidence.",
  "usage-only": "The adapter writes numeric cost or usage observations, but does not infer a recurring subscription without billing evidence.",
  "source-health-only": "The adapter verifies account or service inventory and sync health, but the current provider response has no amount and does not add spend.",
  "setup-ready": "Credentials exist; final configuration or first proven sync is pending.",
  "token-required": "A workspace admin must provide a scoped provider token before sync can run.",
  "oauth-required": "The provider OAuth app has not been configured for this deployment yet.",
  "verification-required": "OAuth is configured, but provider verification is pending before public users can consent.",
  "partner-gated": "Direct sync needs a bank, issuer, PSP, network, or regulated partner agreement.",
  blocked: "A required external dependency is missing; the connector cannot progress in this deployment.",
  "evidence-only": "Covered today through receipts, statements, or user-confirmed manual evidence, not a direct API.",
  planned: "Modeled as a target contract; no adapter has proven a first authorized sync yet.",
};

export function getConnectorSummary() {
  return connectors.reduce<Record<ConnectorStatus, number>>((summary, connector) => {
    summary[connector.status] = (summary[connector.status] ?? 0) + 1;
    return summary;
  }, { live: 0, "ready-with-env": 0, "partner-required": 0, planned: 0 });
}

export function getConnectorSyncSummary() {
  return connectors.reduce(
    (summary, connector) => {
      summary.total += 1;
      summary.realtimeCapable += connector.realtimeCapable ? 1 : 0;
      summary.byAuthType[connector.authType] = (summary.byAuthType[connector.authType] ?? 0) + 1;
      summary.byTrustClass[connector.trustClass] = (summary.byTrustClass[connector.trustClass] ?? 0) + 1;
      return summary;
    },
    {
      total: 0,
      realtimeCapable: 0,
      byAuthType: {} as Record<ConnectorAuthType, number>,
      byTrustClass: {} as Record<ConnectorTrustClass, number>,
    },
  );
}

export function getConnectorById(id: string) {
  return connectors.find((connector) => connector.id === id);
}
