export const customerPhrases = {
  emptyHomeTitle: "Let's review your software stack.",
  emptyHomeBody: "Add a few recent software bills. We'll organize what you're paying for and flag anything worth a closer look.",
  addBills: "Add bills",
  noMailbox: "No mailbox access required.",
  caughtUp: "No decisions due right now.",
  noDecisionsDue: "No decisions due right now.",
  quietHomeTitle: "Nothing to decide right now",
  quietHomeBody: "No charge in the next few days needs a decision.",
  quietHomeNothingExpected: "No charge is expected from the bills you have added.",
  decisionBoundary: "Vognary records your decision. It never cancels a service and never moves money.",
  whyThisNeedsAttention: "Why this needs attention",
  reviewWhen: "When should this come back?",
  noActionNeeded: "No action needed.",
  reviewResults: "Review results",
  seeAllCommitments: "See all commitments",
  keepCurrent: "Keep Vognary current",
  somethingWrong: "Something wrong?",
  seeWhy: "Why?",
  seeTheReceipt: "See the receipt",
  dropzone: "Drop invoices or receipts here",
  readablePdfs: "Text-based PDFs, CSV, and spreadsheet files. Image scans cannot be read.",
  readingInvoice: "Reading your invoice…",
  stayUpToDate: "Stay up to date",
  privateInbox: "Private billing inbox",
  forwardMatching: "Forward matching software bills automatically.",
  addBillManually: "Add a bill manually",
  notSetUp: "Not set up",
  waitingConfirmation: "Waiting for confirmation",
  inboxOn: "On",
  trustOnce: "Vognary does not read your mailbox.",
} as const;

export const cadenceShortLabels = {
  WEEKLY: " / week",
  BIWEEKLY: " / 2 weeks",
  SEMIMONTHLY: " / twice a month",
  MONTHLY: " / month",
  BIMONTHLY: " / 2 months",
  QUARTERLY: " / quarter",
  YEARLY: " / year",
  IRREGULAR: "",
} as const;
