export const customerPhrases = {
  emptyHomeTitle: "Let's review your software stack.",
  emptyHomeBody: "Add a few recent software bills. We'll organize what you're paying for and flag anything worth a closer look.",
  addBills: "Add bills",
  noMailbox: "No mailbox access required.",
  caughtUp: "No decisions due right now.",
  noDecisionsDue: "No decisions due right now.",
  quietHomeTitle: "Nothing to decide right now",
  quietHomeBody: "No charge in the next few days needs a decision.",
  quietHomeNothingExpected: "No charge is expected from the bills you have added.",
  watchingHomeTitle: "Remembered this cycle",
  watchingHomeBody: "Vognary is watching the next window. If the charge matches, this stays quiet. If it doesn't, you will see it.",
  decisionBoundary: "Vognary records your decision. It never cancels a service and never moves money.",
  rememberedThisCycle: "Remembered for this billing cycle. The next matching receipt can verify what happened.",
  whyThisNeedsAttention: "Why a decision is needed now",
  citedEvidence: "From your receipt",
  seeCitedReceipt: "See the cited receipt",
  openCommitment: "Open this commitment",
  copyForCofounder: "Copy this for my cofounder",
  copiedForCofounder: "Copied. Forward it in ten seconds.",
  reviewWhen: "When should this come back?",
  noActionNeeded: "No action needed.",
  reviewResults: "See Home",
  seeAllCommitments: "See all commitments",
  keepCurrent: "Keep Vognary current",
  somethingWrong: "Something wrong?",
  seeWhy: "Why?",
  seeTheReceipt: "See the receipt",
  dropzone: "Drop bills or receipts here",
  readablePdfs: "PDF, CSV, spreadsheet, or bill photo. Vognary extracts the merchant, amount, and date it can verify; you confirm the line.",
  confirmTheLine: "Confirm the merchant, amount, and date. Vognary does not invent those from a photo.",
  confirmPrefill: "Check these fields against the photo. Confirm only if they match. Vognary does not invent money.",
  confirmPartial: "We read part of this bill from the photo. Fill any blank from the image. Confirm only if it matches. Vognary does not invent money.",
  confirmZeroPaid: "This photo shows a paid amount of 0. We did not fill a plan price. Enter the charge you can see, then confirm.",
  imageUnreadable: "This photo was not treated as money. Confirm the line, or paste the receipt text.",
  readingInvoice: "Reading your invoice…",
  stayUpToDate: "Stay up to date",
  privateInbox: "Private billing inbox",
  forwardMatching: "Forward matching software bills automatically.",
  addBillManually: "Add a bill manually",
  notSetUp: "Not set up",
  waitingConfirmation: "Waiting for confirmation",
  inboxOn: "On",
  trustOnce: "Vognary does not read your mailbox.",
} as const;

export const cadenceShortLabels = {
  WEEKLY: " / week",
  BIWEEKLY: " / 2 weeks",
  SEMIMONTHLY: " / twice a month",
  MONTHLY: " / month",
  BIMONTHLY: " / 2 months",
  QUARTERLY: " / quarter",
  YEARLY: " / year",
  IRREGULAR: "",
} as const;
